### ISSUE TITLE
a10_partition fails for all modules

### ISSUE THREAD

**Issue by dgarrick-igt** [a10networks/a10-ansible#111]
Since the change from - partition (which worked great)  to a10_partition it now fails for every module with the follwoing error 

"msg": "argument a10_partition is of type <type 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"}

**Comment by hthompson6** [comment]
The change had to be made due to conflicts with the write mem keyword "partition". I'll be updating the README later today. In the mean time, here's a gist showing new usage: https://gist.github.com/hthompson6/a19260dab90077cc45dc3e5c1d9ae2c0
