### ISSUE TITLE
Device Context

### ISSUE THREAD

**Issue by dgarrick-igt** [a10networks/a10-ansible#123]
I have a pair of A10 configured for VCS.  Using these ansible module I'm unable to apply any configuration to device 2.   All configuration applied to device 1 works correctly.  I use the device-context module to swith to device 2, but all subsequent config is still applied to device 1.  Ansible reports the device-context switch as changed indicating it was sucessful.  However the following commands are marked OK as they are still being applies to context 1 where the config already exists.  Any suggestions, ICMP is just an example, I get the same results for all device 2 configuration.

#
#  Select Device context 2
#
  - name: Set Device context
    a10_device_context:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_user }}"
      a10_password: "{{ a10_pass }}"
      a10_protocol: https
      a10_port: 443
      state: present
      a10_partition:
        name: pos
        shared: 0
      device_id: 2
    tags:
      - context2_icmp

#
# Disable ICMP redirect
#

  - name: Disable ICMP redirect
    a10_ip_icmp:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_user }}"
      a10_password: "{{ a10_pass }}"
      a10_protocol: https
      a10_port: 443
      state: present
      a10_partition:
        name: pos
        shared: 0
      redirect: yes
    tags:
      - context2_icmp

TASK [Set Device context] 
changed: [caslb-pdc]

TASK [Disable ICMP redirect] 
ok: [caslb-pdc]

**Comment by omkar-bhujbal11** [comment]
Thanks for raising this issue. It's been fixed in PR #129.

Instead of 'a10_device_context' module please use '**a10_device_context_id**' _parameter_ 
After pulling the latest version. You should be able to get this to work with:
  - name: Disable ICMP redirect
    a10_ip_icmp:
      a10_device_context_id: 2
      a10_host: "{{ host }}"
      a10_username: "{{ a10_user }}"
      a10_password: "{{ a10_pass }}"
      a10_protocol: https
      a10_port: 443
      state: present
      redirect: no
    tags:
      - context2_icmp

 - name: Change IP Fragmentation Paramater
   a10_ip_frag:
     a10_device_context_id: 10
     a10_host: "{{ host }}"
     a10_username: "{{ a10_user }}"
     a10_password: "{{ a10_pass }}"
     a10_protocol: https
     a10_port: 443
     state: present
     timeout: 2221
   tags:
     - context2_icmp

Feel free to reopen this if the issue persists.
