### ISSUE TITLE
This version doesn't seem to contain a 'write_config' method

### ISSUE THREAD

**Issue by glassrye** [a10networks/a10-ansible#15]
In order to persist the ansible changes through a reboot of the device, a 'write_config' option needs to be implemented. 

It is currently part of Ansible 2.4 A10 modules, but most of those are specific to AXAPI v2.1

**Comment by hthompson6** [comment]
Thanks for raising this issue up. Recent versions have fixed this. Please re-open if you re-encounter this issue.
