### ISSUE TITLE
Can't choose the partition to apply settings

### ISSUE THREAD

**Issue by alantamer** [a10networks/a10-ansible#19]
Hi, with these modules I can't choose the partition to which I would like to apply the settings.

In the official Ansible modules this is available with the "partition" clause.

Is there any roadmap to implement this?

**Comment by dgarrick-igt** [comment]
Has this been addressed.  I have the same in that I cannot apply configuration to any partition other than shared.  Checked out the partition and active partition modules which don't work.  So I've now way to use all these modules.

**Comment by mdurrant-b3** [comment]
The `partition` entry requires that the partition exist. As Ansible requires connecting to AXAPI, issuing the command. and disconnecting, we activate the correct partition at the beginning of every operation.

For example, if we have partition `asdf` (it must exist already), using:
`partition: asdf` 
in our playbook results in partition `asdf` being activated before the operation.

**Comment by hthompson6** [comment]
This issue has been patched out. Further information regarding partitioning found on ReadMe.
