### ISSUE TITLE
Common bugs when referring module.params

### ISSUE THREAD

**Issue by kishizuka4989** [a10networks/a10-ansible#23]
Almost all modules include the line to refer module.params with wrong argument in existing_url function as follows:
f_dict["vlan-num"] = module.params["vlan-num"]

But" vlan-num" should be "vlan_num" due to playbook's yaml restriction.
They should be revised.

**Comment by dgarrick-igt** [comment]
Still unable to select active partition for configuration.  Used above a10_partition module which fails.  On examination module.params["partition-name"] still using -.  Shoud it not be module.params["partition_name"].  If I change this manually I get the error "msg": "Method not allowed".

**Comment by kishizuka4989** [comment]
Hi @dgarrick-igt , 

This might occur if you update the existing partition. 
Since aXAPI for partition does not allow PUT method for update, so we need to modify line 267 in a10_partition.py module as follows.
Before: post_result = module.client.put(existing_url(module), payload)
After: post_result = module.client.post(existing_url(module), payload)

I hope it works.

**Comment by hthompson6** [comment]
Fixed in recent versions. Closing due to age. Please re-open if you encounter again.
