### ISSUE TITLE
Reference to 'module' invalid during imports

### ISSUE THREAD

**Issue by jgherbert** [a10networks/a10-ansible#51]
Correct me if I'm wrong (it's entirely possible)_, but this code, which appears in many - all? - of the files in library/:

```
# our imports go at the top so we fail fast.
try:
    from a10_ansible import errors as a10_ex
    from a10_ansible.axapi_http import client_factory, session_factory
    from a10_ansible.kwbl import KW_IN, KW_OUT, translate_blacklist as translateBlacklist

except (ImportError) as ex:
    module.fail_json(msg="Import Error:{0}".format(ex))
except (Exception) as ex:
    module.fail_json(msg="General Exception in Ansible module import:{0}".format(ex))

```

...has a dependency on 'module' in the except clauses. Unfortunately, if I read it correctly, 'module' isn't defined until main() is run, which is *after* the imports are processed. Therefore if any of the imports fail, rather than giving a nice error, we get an error complaining that the name 'module' is undefined.

This is likely similar or the same issue as raised in #42; but seems like it might need an eye on the code. Or to tell me what I'm missing, of course ;)

Thank you!

**Comment by sebw** [comment]
Noticed this here too.

**Comment by ddobrescu** [comment]
I am getting the same error but wasn't able to fix it . Could you please provide some help please 
I am trying to run this in a docker container for AWX if that helps . Is there any issue with the Python version ? I have placed the modules under /usr/share/ansible/plugins/modules

`[root@awx _6__iam_tmo]# ansible-playbook -C -D -vvv a10_pool.yaml 
ansible-playbook 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  **python version = 2.7.5** (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: a10_pool.yaml ********************************************************************************************************************************************************************
1 plays in a10_pool.yaml

PLAY [A10 Server and pools] ****************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
task path: /var/lib/awx/projects/_6__iam_tmo/a10_pool.yaml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351 `" && echo ansible-tmp-1553367325.17-240230819403351="` echo /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12457ndoqqb/tmppJr0jC TO /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351/ /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1553367325.17-240230819403351/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Create Server in SLB_Servers] ********************************************************************************************************************************************************
task path: /var/lib/awx/projects/_6__iam_tmo/a10_pool.yaml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685 `" && echo ansible-tmp-1553367336.01-148107114222685="` echo /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685 `" ) && sleep 0'
Using module file /usr/share/ansible/plugins/modules/a10_modules/library/a10_slb_server.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12457ndoqqb/tmpMLrw1Z TO /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/ /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_a10_slb_server_payload_OolDMP/__main__.py", line 235, in <module>
NameError: name 'module' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1553367336.01-148107114222685/AnsiballZ_a10_slb_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_a10_slb_server_payload_OolDMP/__main__.py\", line 235, in <module>\nNameError: name 'module' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
`
Thank you a lot !

**Comment by ddobrescu** [comment]
I had the same issue with the default python in AWX. When I was trying to run it was getting module not defined. Seems that the issue is in axapi_http.py when it was trying to import "import requests" as this was missing in my system.  You can try it out on your system by running python -c "import requests". If you dont have it , you can run pip install requests . Hope this helps someone, spend a few good hours to troubleshoot it :)

**Comment by mdurrant-b3** [comment]
`module` is defined in the "shim" that delegates to our module. When it's undefined, that indicates an exception outside of us has been raised.

This is a problem with a number of the Ansible 2.7.x releases. I found reverting to later 2.6.x releases resulted in a functional system.

Ironically, putting external library imports at the bottom is supposed to ensure this doesn't happen... we should be seeing the failure that causes `module` to not get assigned before our code is even in the picture.

**Comment by hthompson6** [comment]
Fixed. As @ddobrescu stated issues with failing to import module usually is due to not having requests installed. Other issues are around not having a10-ansible installed and referenced as a library.
