### ISSUE TITLE
Diagnose problem with 

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-ansible#55]
Stack trace: ```fatal: [all]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1553745455.8-25498037904054/AnsiballZ_a10_slb_virtual_server_port.py\", line 261, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1553745455.8-25498037904054/AnsiballZ_a10_slb_virtual_server_port.py\", line 251, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1553745455.8-25498037904054/AnsiballZ_a10_slb_virtual_server_port.py\", line 119, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 883, in <module>\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 875, in main\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 863, in run_command\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 758, in exists\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 754, in get\n  File \"/tmp/ansible_a10_slb_virtual_server_port_payload_59r4cA/__main__.py\", line 678, in existing_url\nKeyError: 'port-number'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Playbook: ```- hosts: all
  name: "Create a10_slb_virtual_server_port example playbook"
  connection: local
  tasks:
  - name: Create a10_slb_virtual_server instance
    a10_slb_virtual_server:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: 443
      a10_protocol: https
      ip_address: 192.168.42.1
      netmask: 255.255.255.0
      name: vs1
      #      vrid: 1
      enable_disable_action: disable-when-all-ports-down

  - name: Associate virtual port
    a10_slb_virtual_server_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: 443
      a10_protocol: https
      state: present
      virtual_server_name: vs1
      protocol: "tcp"
      port_number: 80
      #      pool: "natproxy2"
      service_group: sg1_80
      # template_persist_source_ip: source-ip_30min
      ha_conn_mirror: 1
      # template_tcp: session-aging-5min_tcp
      auto: 1```

**Comment by hthompson6** [comment]
Fixed
