### ISSUE TITLE
No Support for aXAPI Version 3.0

### ISSUE THREAD

**Issue by Aaron-ML** [a10networks/a10-ansible#6]

**Comment by aaronmlucas** [comment]
On the docs it shows only support for aXAPI 2.1, when I run my playbook on aXAPI 3.0 A10 Appliance I get the following...

`TASK [a10_server] ***************************************************************************************************
task path: /etc/ansible/a10-disable-test.yml:3
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/a10/a10_server.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939 `" && echo ansible-tmp-1508185896.69-71893879258939="` echo /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpQfF6_Z TO /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939/a10_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939/ /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939/a10_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939/a10_server.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1508185896.69-71893879258939/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "client_cert": null,
            "client_key": null,
            "force": false,
            "force_basic_auth": false,
            "host": "CN-A10-2",
            "http_agent": "ansible-httpget",
            "partition": "[]",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "server_ip": null,
            "server_name": "test",
            "server_ports": [],
            "server_status": "disabled",
            "state": "present",
            "url": null,
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "username": "ansible_a10",
            "validate_certs": false,
            "write_config": false
        }
    },
    "msg": "failed to connect (status code 404), error was HTTP Error 404: Not Found"
`

**Comment by aaronmlucas** [comment]
Thanks for the response.

**Comment by mdurrant-b3** [comment]
@aaronmlucas My sincerest apologies for failing to respond. I had closed existing issues as we're replacing our a10-ansible codebase wholesale with code automatically generated from our AXAPI v3.0 schema files. 

This is currently available in the `sdk_testing` branch in this repository.

Again, my sincerest apologies for not responding when you first posted the issue. Thank you for bringing my attention to this.  

@booneosborn - Tagging you as my failure in this regard should not go unnoticed.

**Comment by movergan** [comment]
Hi guys. I'm facing the same issue. Need it very badly. Will take a look at the sdk_testing  branch.

**Comment by hthompson6** [comment]
Issue seems to have been resolved. Closing due to age. Please re-open if issue persists.
