### ISSUE TITLE
getting nNameError: name 'module' is not defined while running any ansible playbook

### ISSUE THREAD

**Issue by arun-10** [a10networks/a10-ansible#66]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'module' is not defined
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_F4TsRV/ansible_module_a10_monitor.py\", line 133, in <module>\n    module.fail_json(msg=\"Import Error:{0}\".format(ex))\nNameError: name 'module' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by hthompson6** [comment]
Usually comes from the `requests` library not being installed. PR#71 addresses this.
