### ISSUE TITLE
Can't specify local cert in a10_slb_template_client_ssl: 

### ISSUE THREAD

**Issue by dgarrick-igt** [a10networks/a10-ansible#97]
Can't reference my local ssl_cert in when creating a client ssl template.  cert and key are not valid options.  cert_str and key_str report json field failure 

msg": "Failed to handle json field \"cert-str\". JSON field cannot be handled. It might be undefined or disabled by other fields."

**Comment by jacirbadillo** [comment]
Same issue here!

**Comment by hthompson6** [comment]
Apologies. I believe this had been escalated to our TAC team and solved there, but I hadn't replied here.

This has been caused by a difference in AXAP version between ACOSv411 and ACOSv414. I've included a 4_1_1 branch found here: https://github.com/a10networks/a10-ansible/tree/4_1_1
