### ISSUE TITLE
Can't specify partition: "all" or "specified" in a10_write_memory.py as part of memory module.

### ISSUE THREAD

**Issue by blatzheimp** [a10networks/a10-ansible#99]
-- ansible-playbook -vvv output
[louisb@controller a10-ansible]$ ansible-playbook -i inventory -l vTH3 a10_write_memory_playbook.yaml -vvvv   
ansible-playbook 2.6.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/louisb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/louisb/a10-ansible/inventory/a10.yaml inventory source with yaml plugin
Parsed /home/louisb/a10-ansible/inventory/vips.yaml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: a10_write_memory_playbook.yaml *************************************************************************************************************************************************************************************************
1 plays in a10_write_memory_playbook.yaml

PLAY [Write Memory] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************
task path: /home/louisb/a10-ansible/a10_write_memory_playbook.yaml:3
<vTH3> ESTABLISH LOCAL CONNECTION FOR USER: louisb
<vTH3> EXEC /bin/sh -c 'echo ~louisb && sleep 0'
<vTH3> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219 `" && echo ansible-tmp-1568932553.93-185873504332219="` echo /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<vTH3> PUT /home/louisb/.ansible/tmp/ansible-local-4375iIAcnU/tmpzwdy1z TO /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219/setup.py
<vTH3> EXEC /bin/sh -c 'chmod u+x /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219/ /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219/setup.py && sleep 0'
<vTH3> EXEC /bin/sh -c '/usr/bin/python /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219/setup.py && sleep 0'
<vTH3> EXEC /bin/sh -c 'rm -f -r /home/louisb/.ansible/tmp/ansible-tmp-1568932553.93-185873504332219/ > /dev/null 2>&1 && sleep 0'
ok: [vTH3]
META: ran handlers

TASK [Save Running to Startup] ***********************************************************************************************************************************************************************************************************
task path: /home/louisb/a10-ansible/a10_write_memory_playbook.yaml:7
<vTH3> ESTABLISH LOCAL CONNECTION FOR USER: louisb
<vTH3> EXEC /bin/sh -c 'echo ~louisb && sleep 0'
<vTH3> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599 `" && echo ansible-tmp-1568932555.15-122246082370599="` echo /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599 `" ) && sleep 0'
Using module file /usr/share/ansible/plugins/modules/a10_ansible/library/a10_write_memory.py
<vTH3> PUT /home/louisb/.ansible/tmp/ansible-local-4375iIAcnU/tmp9IP0Ci TO /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599/a10_write_memory.py
<vTH3> EXEC /bin/sh -c 'chmod u+x /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599/ /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599/a10_write_memory.py && sleep 0'
<vTH3> EXEC /bin/sh -c '/usr/bin/python /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599/a10_write_memory.py && sleep 0'
<vTH3> EXEC /bin/sh -c 'rm -f -r /home/louisb/.ansible/tmp/ansible-tmp-1568932555.15-122246082370599/ > /dev/null 2>&1 && sleep 0'
fatal: [vTH3]: FAILED! => {
    "changed": false, 
    "module_stderr": "No handlers could be found for logger \"a10_ansible.axapi_http\"\n/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_3K0WYT/ansible_module_a10_write_memory.py\", line 344, in <module>\n    main()\n  File \"/tmp/ansible_3K0WYT/ansible_module_a10_write_memory.py\", line 336, in main\n    result = run_command(module)\n  File \"/tmp/ansible_3K0WYT/ansible_module_a10_write_memory.py\", line 317, in run_command\n    module.client.activate_partition(partition)\n  File \"/usr/lib/python2.7/site-packages/a10_ansible/axapi_http.py\", line 307, in activate_partition\n    raise Exception(\"Could not activate {0}\".format(partition_name))\nException: Could not activate all\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
vTH3                       : ok=1    changed=0    unreachable=0    failed=1   

-- playbook file -- 
---
# Save running configuration to startup configuration -- write memory
- name: Write Memory
  connection: local
  hosts: a10
  tasks:
  - name: Save Running to Startup
    a10_write_memory:
      a10_host: "{{ a10_host }}"
      a10_password: "{{ a10_password }}"
      a10_username: "{{ a10_username }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      destination: "local"
      partition: "all"

If i use partition: "shared" -- it works because it calls active-partition.

 -- Inventory
---
# A10 Inventory File
all:
  children:
    a10:
     hosts:
      vTH1:
       a10_host: "192.168.133.11"
       hostname: "vThunder1"
      vTH2:
       a10_host: "192.168.133.12"
       hostname: "vThunder2"
      vTH3:
       a10_host: "192.168.133.13"
       hostname: "vThunder3"
     vars:
       a10_username: "admin"
       a10_password: "a10"
       a10_protocol: "https"
       a10_port: 443
       dns_suffix: "lab.blatzheim.us"
       dns_primary: "192.168.133.1"
       dns_secondary: "8.8.8.8"
    NorthAmerica:
     children:
       Central:
         vars:
           timezone: "America/Chicago"
           ntp_server: "us.pool.ntp.org"
         hosts:
           vTH1:
           vTH2:
           vTH3:
~

**Comment by jacirbadillo** [comment]
I have the same issue:

TASK [write mem] **********************************************************************************************************************************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"a10_ansible.axapi_http\"\n/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible__4X9WI/ansible_module_a10_write_memory.py\", line 330, in <module>\n    main()\n  File \"/tmp/ansible__4X9WI/ansible_module_a10_write_memory.py\", line 322, in main\n    result = run_command(module)\n  File \"/tmp/ansible__4X9WI/ansible_module_a10_write_memory.py\", line 308, in run_command\n    module.client.activate_partition(partition)\n  File \"/home/user1/ansible/a10-ansible/a10_ansible/axapi_http.py\", line 307, in activate_partition\n    raise Exception(\"Could not activate {0}\".format(partition_name))\nException: Could not activate all\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by hthompson6** [comment]
Fixed in PR #104

**Comment by blatzheimp** [comment]
👍
